/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tecmis;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public final class Adduseradmin extends javax.swing.JFrame {

    /**
     * Creates new form Adduseradmin
     */
    
    DB db = new DB();
    Users us = new Users();
    
    
            
            
    public Adduseradmin() {
        
        initComponents();
        
        db.getconnect();
        
        setdatatotable();
    }
    
    
    public void setdatatotable(){
        try {
            DefaultTableModel model = (DefaultTableModel)utable.getModel();
            
            String qu = "SELECT * FROM users";
            ResultSet rs = db.stm.executeQuery(qu);
            
            while(rs.next()){
                Object[] row = {rs.getString("id_num"),rs.getString("name"),rs.getString("email"),rs.getInt("tel"),rs.getString("gender")};
                model.addRow(row);
                
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Adduseradmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pwd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cpwd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        level = new javax.swing.JComboBox<>();
        adduserbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        adduserreset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        adminuserupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        utable = new javax.swing.JTable();
        adminuserdelete = new javax.swing.JButton();
        sutext = new javax.swing.JLabel();
        adminuseredit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User profiles");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 156, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMinimumSize(new java.awt.Dimension(270, 550));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Add User");

        jLabel3.setText("Name");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel4.setText("Password");

        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });

        jLabel5.setText("Comfirm Password");

        cpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpwdActionPerformed(evt);
            }
        });

        jLabel6.setText("Roll");

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Technical Officer", "Lecturer", "Student" }));
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });

        adduserbtn.setBackground(new java.awt.Color(255, 0, 255));
        adduserbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adduserbtn.setForeground(new java.awt.Color(255, 255, 255));
        adduserbtn.setText("ADD");
        adduserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserbtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Email");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel8.setText("Phone Number");

        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });

        jLabel9.setText("Gender");

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        adduserreset.setBackground(new java.awt.Color(204, 0, 51));
        adduserreset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adduserreset.setForeground(new java.awt.Color(255, 255, 255));
        adduserreset.setText("Reset");
        adduserreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserresetActionPerformed(evt);
            }
        });

        jLabel10.setText("ID Number");

        adminuserupdate.setBackground(new java.awt.Color(102, 102, 102));
        adminuserupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adminuserupdate.setForeground(new java.awt.Color(255, 255, 255));
        adminuserupdate.setText("Update");
        adminuserupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminuserupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(pwd)
                                .addComponent(cpwd)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(level, 0, 191, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addComponent(id)
                                .addComponent(jLabel8))
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(adduserbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(adduserreset)))))
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(adminuserupdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adduserbtn)
                    .addComponent(adduserreset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminuserupdate)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 580));

        utable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Phone Number", "Gender"
            }
        ));
        jScrollPane1.setViewportView(utable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 122, 550, 420));

        adminuserdelete.setBackground(new java.awt.Color(255, 0, 255));
        adminuserdelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adminuserdelete.setText("Delete");
        adminuserdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminuserdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(adminuserdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 78, -1, -1));

        sutext.setBackground(new java.awt.Color(0, 255, 255));
        sutext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(sutext, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 280, 30));

        adminuseredit.setBackground(new java.awt.Color(255, 0, 255));
        adminuseredit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adminuseredit.setText("Edit");
        adminuseredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminusereditActionPerformed(evt);
            }
        });
        jPanel1.add(adminuseredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adduserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserbtnActionPerformed
        // TODO add your handling code here:
            us.setId(id.getText());
            us.setName(name.getText());
            us.setEmail(email.getText());
            us.setPassword(pwd.getText());
            us.setTel(tel.getText());
            us.setGender(gender.getSelectedItem().toString());
            String roll = level.getSelectedItem().toString();
            
            
            
            switch (roll) {
                case "Admin":
                    us.setLevel("1");
                    break;
                case "Technical Officer":
                    us.setLevel("2");
                    break;
                case "Lecturer":
                    us.setLevel("3");
                    break;
                case "Student":
                    us.setLevel("4");
                    break;
                default:
                    break;
            }
            
            
        
        try {
            
            if(us.getId().equals("") || us.getName().equals("") || us.getEmail().equals("") || us.getPassword().equals("")|| us.getTel().equals("")|| us.getGender().equals("")){
                sutext.setText("Error in getting data");
                
            }else{
                if (us.getPassword().equals(cpwd.getText())) {
                   String sql = "insert into users (id_num,name,email,password,tel,gender,level) values ('"+us.getId()+"','"+us.getName()+"','"+us.getEmail()+"','"+us.getPassword()+"','"+us.getTel()+"','"+us.getGender()+"','"+us.getLevel()+"')";
                
                    int res = db.stm.executeUpdate(sql);
                    if (res > 0) {
                        sutext.setText("User added Successfully");
                        DefaultTableModel dtm = (DefaultTableModel)utable.getModel();
                        
                        String[] items = {us.getId(),us.getName(),us.getEmail(),us.getTel(),us.getGender()};
                        dtm.addRow(items);
                        
                        id.setText("");
                        name.setText("");
                        email.setText("");
                        pwd.setText("");
                        cpwd.setText("");
                        tel.setText("");
                        
                    }else{
                        sutext.setText("database error");
                    } 
                }else{
                    sutext.setText("The passwors are did not match");
                }
            }
        } catch (Exception e) {
            sutext.setText("Did not run try");
        }
    }//GEN-LAST:event_adduserbtnActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void cpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwdActionPerformed

    private void adduserresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserresetActionPerformed
        id.setText("");
        name.setText("");
        email.setText("");
        pwd.setText("");
        cpwd.setText("");
        tel.setText("");
       
    }//GEN-LAST:event_adduserresetActionPerformed

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelActionPerformed

    private void adminuserdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminuserdeleteActionPerformed
        // TODO add your handling code here:
        int drow = utable.getSelectedRow();
        
        if(drow > 0){
            String uid = (String) utable.getValueAt(drow, 0);
                       
            DefaultTableModel model = (DefaultTableModel)utable.getModel();
            model.removeRow(drow);
            
            String dsql = "delete from users where id_num ='"+uid+"'";
            
            try {
                int rest = db.stm.executeUpdate(dsql);
                if(rest > 0){
                    sutext.setText("Deleted successfully");
                }else{
                    sutext.setText("Deleted Unsuccessfully");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Adduseradmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            sutext.setText("Select a row");
        }
    }//GEN-LAST:event_adminuserdeleteActionPerformed

    private void adminusereditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminusereditActionPerformed
        // TODO add your handling code here:
        int row = utable.getSelectedRow();
        if(row>0){
            
            id.setText((String) utable.getValueAt(row, 0));
            name.setText((String) utable.getValueAt(row, 1));
            email.setText((String) utable.getValueAt(row, 2));
            tel.setText((String) utable.getValueAt(row, 3));
            
        }else{
            sutext.setText("Select a row");
        }
    }//GEN-LAST:event_adminusereditActionPerformed

    private void adminuserupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminuserupdateActionPerformed
        // TODO add your handling code here:
            us.setId(id.getText());
            us.setName(name.getText());
            us.setEmail(email.getText());
            us.setPassword(pwd.getText());
            us.setTel(tel.getText());
            us.setGender(gender.getSelectedItem().toString());
            String roll = level.getSelectedItem().toString();
            
            
            
            switch (roll) {
                case "Admin":
                    us.setLevel("1");
                    break;
                case "Technical Officer":
                    us.setLevel("2");
                    break;
                case "Lecturer":
                    us.setLevel("3");
                    break;
                case "Student":
                    us.setLevel("4");
                    break;
                default:
                    break;
            }
            
            
        
        try {
            
            if(us.getId().equals("") || us.getName().equals("") || us.getEmail().equals("") || us.getPassword().equals("")|| us.getTel().equals("")|| us.getGender().equals("")){
                sutext.setText("Error in getting data");
                
            }else{
                if (us.getPassword().equals(cpwd.getText())) {
                   String sql = "insert into users (id_num,name,email,password,tel,gender,level) values ('"+us.getId()+"','"+us.getName()+"','"+us.getEmail()+"','"+us.getPassword()+"','"+us.getTel()+"','"+us.getGender()+"','"+us.getLevel()+"')";
                
                    int res = db.stm.executeUpdate(sql);
                    if (res > 0) {
                        sutext.setText("User added Successfully");
                        DefaultTableModel dtm = (DefaultTableModel)utable.getModel();
                        
                        String[] items = {us.getId(),us.getName(),us.getEmail(),us.getTel(),us.getGender()};
                        dtm.addRow(items);
                        
                        id.setText("");
                        name.setText("");
                        email.setText("");
                        pwd.setText("");
                        cpwd.setText("");
                        tel.setText("");
                        
                    }else{
                        sutext.setText("database error");
                    } 
                }else{
                    sutext.setText("The passwors are did not match");
                }
            }
        } catch (Exception e) {
            sutext.setText("Did not run try");
        }
        
    }//GEN-LAST:event_adminuserupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adduseradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adduseradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adduseradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adduseradmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adduseradmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adduserbtn;
    private javax.swing.JButton adduserreset;
    private javax.swing.JButton adminuserdelete;
    private javax.swing.JButton adminuseredit;
    private javax.swing.JButton adminuserupdate;
    private javax.swing.JTextField cpwd;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pwd;
    private javax.swing.JLabel sutext;
    private javax.swing.JTextField tel;
    private javax.swing.JTable utable;
    // End of variables declaration//GEN-END:variables

    private void setText(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
