/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tecmis;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public final class Adminnotice extends javax.swing.JFrame {

    /**
     * Creates new form Adminnotice
     */
    
    DB db = new DB();
    Notices nt = new Notices();
    public int nid;
    
    
    public Adminnotice() {
        initComponents();
        db.getconnect();
        
        getnoticedata();
    }
    
    public void getnoticedata(){
        try {
            DefaultTableModel model = (DefaultTableModel)ntable.getModel();
            
            String qu = "SELECT * FROM notices ORDER BY id DESC";
            ResultSet rs = db.stm.executeQuery(qu);
            
            while(rs.next()){
                Object[] row = {rs.getString("topic"),rs.getString("msg"),rs.getString("ndep"),rs.getString("ndate")};
                model.addRow(row);
                
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Adduseradmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        topic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nodep = new javax.swing.JTextField();
        addnote = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextArea();
        notireset = new javax.swing.JButton();
        notiup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ntable = new javax.swing.JTable();
        notidelete = new javax.swing.JButton();
        notiedit = new javax.swing.JButton();
        ntext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Notice profiles");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Add Notice");

        jLabel3.setText("Topic");

        topic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicActionPerformed(evt);
            }
        });

        jLabel4.setText("Notice");

        jLabel5.setText("Department ID");

        addnote.setBackground(new java.awt.Color(255, 0, 255));
        addnote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addnote.setForeground(new java.awt.Color(255, 255, 255));
        addnote.setText("ADD");
        addnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnoteActionPerformed(evt);
            }
        });

        note.setColumns(20);
        note.setRows(5);
        jScrollPane2.setViewportView(note);

        notireset.setBackground(new java.awt.Color(204, 0, 204));
        notireset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        notireset.setForeground(new java.awt.Color(255, 255, 255));
        notireset.setText("Reset");
        notireset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notiresetActionPerformed(evt);
            }
        });

        notiup.setBackground(new java.awt.Color(204, 0, 153));
        notiup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        notiup.setForeground(new java.awt.Color(255, 255, 255));
        notiup.setText("Update");
        notiup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notiupActionPerformed(evt);
            }
        });

        jLabel6.setText("Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(day, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(topic, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nodep, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(addnote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notireset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notiup)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nodep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addnote)
                    .addComponent(notireset)
                    .addComponent(notiup))
                .addGap(33, 33, 33))
        );

        ntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Topic", "Note", "Department", "Date"
            }
        ));
        jScrollPane1.setViewportView(ntable);

        notidelete.setBackground(new java.awt.Color(255, 0, 255));
        notidelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        notidelete.setForeground(new java.awt.Color(255, 255, 255));
        notidelete.setText("Delete");
        notidelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notideleteActionPerformed(evt);
            }
        });

        notiedit.setBackground(new java.awt.Color(153, 0, 153));
        notiedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        notiedit.setForeground(new java.awt.Color(255, 255, 255));
        notiedit.setText("Edit");
        notiedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notieditActionPerformed(evt);
            }
        });

        ntext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ntext, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(notidelete)
                                .addGap(18, 18, 18)
                                .addComponent(notiedit)))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ntext, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notidelete)
                            .addComponent(notiedit))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnoteActionPerformed
        // TODO add your handling code here:
        nt.setTopic(topic.getText());
        nt.setMsg(note.getText());
        nt.setNdep(nodep.getText());
        nt.setNdate(day.getText());
        
        try {
            
            if(nt.getTopic().equals("") || nt.getMsg().equals("") || nt.getNdep().equals("") || nt.getNdate().equals("")){
                ntext.setText("Fill the all filds");
                
            }else{
                
                   String sql = "insert into notices (topic,msg,ndep,ndate) values ('"+nt.getTopic()+"','"+nt.getMsg()+"','"+nt.getNdep()+"','"+nt.getNdate()+"')";
                   System.out.println(sql);
                    int res = db.stm.executeUpdate(sql);
                    if (res > 0) {
                        ntext.setText("Notice added Successfully");
                        DefaultTableModel dtm = (DefaultTableModel)ntable.getModel();
                        
                        String[] items = {nt.getTopic(),nt.getMsg(),nt.getNdep(),nt.getNdate()};
                        dtm.addRow(items);
                        
                        topic.setText("");
                        note.setText("");
                        nodep.setText("");
                        day.setText("");
                        
                        
                    }else{
                        ntext.setText("database error");
                    } 
                
            }
        } catch (Exception e) {
            ntext.setText("Did not run try");
        }
        
    }//GEN-LAST:event_addnoteActionPerformed

    private void topicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicActionPerformed

    private void notieditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notieditActionPerformed
        // TODO add your handling code here:
        int row = ntable.getSelectedRow();
        if(row>0){
            
            try {
                String stopic = (String) ntable.getValueAt(row, 0);
                String dep = (String) ntable.getValueAt(row, 2);
                
                String qu = "SELECT * FROM notices where topic = '"+stopic+"' AND ndep = '"+dep+"'";
                ResultSet rs = db.stm.executeQuery(qu);
                
                while(rs.next()){
                    nid = rs.getInt("id");
                    this.topic.setText(rs.getString("topic"));
                    this.note.setText(rs.getString("msg"));
                    this.nodep.setText(rs.getString("ndep"));
                    this.day.setText(rs.getString("ndate"));
                    
                    DefaultTableModel dtm = (DefaultTableModel)ntable.getModel();
                    dtm.removeRow(row);
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(Adduseradmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }else{
            ntext.setText("Select a row");
        }
    }//GEN-LAST:event_notieditActionPerformed

    private void notiupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notiupActionPerformed
        // TODO add your handling code here:
        nt.setTopic(topic.getText());
        nt.setMsg(note.getText());
        nt.setNdep(nodep.getText());
        nt.setNdate(day.getText());
        
        try {
            
            if(nt.getTopic().equals("") || nt.getMsg().equals("") || nt.getNdep().equals("") || nt.getNdate().equals("")){
                ntext.setText("Fill the all filds");
                
            }else{
                
                   String upsql = "UPDATE notices SET topic = ?, msg = ?, ndep = ?, ndate = ? WHERE id = ?";
                   //String sql = "insert into users (id_num,name,email,password,tel,gender,level) values ('"+us.getId()+"','"+us.getName()+"','"+us.getEmail()+"','"+us.getPassword()+"','"+us.getTel()+"','"+us.getGender()+"','"+us.getLevel()+"')";
                   System.out.println("sql work");
                   PreparedStatement st = db.conn.prepareStatement(upsql);
                   
                   st.setString(1, nt.getTopic());
                   st.setString(2, nt.getMsg());
                   st.setString(3, nt.getNdep());
                   st.setString(4, nt.getNdate());
                   st.setInt(5, nid);
                   
                    int res = st.executeUpdate();
                   
                    if (res > 0) {
                        ntext.setText("Notices Updated Successfully");
                        DefaultTableModel dtm = (DefaultTableModel)ntable.getModel();
                        
                        String[] items = {nt.getTopic(),nt.getMsg(),nt.getNdep(),nt.getNdate()};
                        dtm.addRow(items);
                        
                        topic.setText("");
                        note.setText("");
                        nodep.setText("");
                        day.setText("");
                        
                    }else{
                        ntext.setText("database error");
                    } 
                
            }
        } catch (Exception e) {
            ntext.setText("Did not run try");
        }
        
    }//GEN-LAST:event_notiupActionPerformed

    private void notiresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notiresetActionPerformed
        // TODO add your handling code here:
        topic.setText("");
        note.setText("");
        nodep.setText("");
        day.setText("");
    }//GEN-LAST:event_notiresetActionPerformed

    private void notideleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notideleteActionPerformed
        // TODO add your handling code here:
        int drow = ntable.getSelectedRow();
        
        if(drow > 0){
            String dtopic = (String) ntable.getValueAt(drow, 0);
            String ddep = (String) ntable.getValueAt(drow, 2);
                       
            DefaultTableModel model = (DefaultTableModel)ntable.getModel();
            model.removeRow(drow);
            
            String dsql = "delete from notices where topic ='"+dtopic+"' AND ndep = '"+ddep+"'";
            
            try {
                int rest = db.stm.executeUpdate(dsql);
                if(rest > 0){
                    ntext.setText("Deleted successfully");
                }else{
                    ntext.setText("Deleted Unsuccessfully");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Adduseradmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            ntext.setText("Select a row");
        }
    }//GEN-LAST:event_notideleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminnotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminnotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminnotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminnotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminnotice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnote;
    private javax.swing.JTextField day;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nodep;
    private javax.swing.JTextArea note;
    private javax.swing.JButton notidelete;
    private javax.swing.JButton notiedit;
    private javax.swing.JButton notireset;
    private javax.swing.JButton notiup;
    private javax.swing.JTable ntable;
    private javax.swing.JLabel ntext;
    private javax.swing.JTextField topic;
    // End of variables declaration//GEN-END:variables
}
