/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package tecmis;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Coursetolec extends javax.swing.JFrame {

    /** Creates new form Coursetolec */
    
    DB db = new DB();
    
    public Coursetolec() {
        initComponents();
        
        db.getconnect();
        
        datatota();
    }
    
    
    public void datatota(){
        try {
            DefaultTableModel model = (DefaultTableModel)cltable.getModel();
            
            String qu = "SELECT * FROM courselecs";
            ResultSet rs = db.stm.executeQuery(qu);
            
            while(rs.next()){
                Object[] row = {rs.getString("cl_cid"),rs.getString("cl_lid")};
                model.addRow(row);
                
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Adduseradmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cllid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clcid = new javax.swing.JTextField();
        cladd = new javax.swing.JButton();
        clreset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cltable = new javax.swing.JTable();
        cldelete = new javax.swing.JButton();
        cltext = new javax.swing.JLabel();
        clcan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Lecture to Course");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lecture ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course ID");

        cladd.setBackground(new java.awt.Color(204, 0, 204));
        cladd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cladd.setForeground(new java.awt.Color(255, 255, 255));
        cladd.setText("Add");
        cladd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claddActionPerformed(evt);
            }
        });

        clreset.setBackground(new java.awt.Color(153, 0, 153));
        clreset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clreset.setForeground(new java.awt.Color(255, 255, 255));
        clreset.setText("Reset");
        clreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cladd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(clreset))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(cllid)
                    .addComponent(clcid))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cllid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cladd)
                    .addComponent(clreset))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        cltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Course ID", "Lectiure ID"
            }
        ));
        jScrollPane1.setViewportView(cltable);

        cldelete.setBackground(new java.awt.Color(204, 0, 0));
        cldelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cldelete.setForeground(new java.awt.Color(255, 255, 255));
        cldelete.setText("DELETE");
        cldelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cldeleteActionPerformed(evt);
            }
        });

        cltext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        clcan.setText("cancel");
        clcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clcanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cldelete))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cltext, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clcan)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cltext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clcan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cldelete)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void claddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claddActionPerformed
        // TODO add your handling code here:
        String cid = clcid.getText();
        String lid = cllid.getText();
        
        try {
            
            if(cid.equals("") || lid.equals("")){
                cltext.setText("Error in getting data");
                
            }else{
                
                   String sql = "insert into courselecs (cl_cid,cl_lid) values ('"+cid+"','"+lid+"')";
                
                    int res = db.stm.executeUpdate(sql);
                    if (res > 0) {
                        cltext.setText("Lecture added to course Successfully");
                        DefaultTableModel dtm = (DefaultTableModel)cltable.getModel();
                        
                        String[] items = {cid,lid};
                        dtm.addRow(items);
                        
                        clcid.setText("");
                        cllid.setText("");
                        
                        
                    }else{
                        cltext.setText("database error");
                   
            }
            }
        } catch (Exception e) {
            cltext.setText("Did not run try");
        }
    }//GEN-LAST:event_claddActionPerformed

    private void cldeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cldeleteActionPerformed
        // TODO add your handling code here:
        int drow = cltable.getSelectedRow();
        
        if(drow > 0){
            String ccid = (String) cltable.getValueAt(drow, 0);
            String clid = (String) cltable.getValueAt(drow, 1);
                       
            DefaultTableModel model = (DefaultTableModel)cltable.getModel();
            model.removeRow(drow);
            
            String dsql = "delete from courselecs where cl_cid ='"+ccid+"' and cl_lid = '"+clid+"'";
            
            try {
                int rest = db.stm.executeUpdate(dsql);
                if(rest > 0){
                    cltext.setText("Deleted successfully");
                }else{
                    cltext.setText("Deleted Unsuccessfully");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Adduseradmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            cltext.setText("Select a row");
        }
    }//GEN-LAST:event_cldeleteActionPerformed

    private void clresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clresetActionPerformed
        // TODO add your handling code here:
        clcid.setText("");
        cllid.setText("");
    }//GEN-LAST:event_clresetActionPerformed

    private void clcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clcanActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_clcanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coursetolec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coursetolec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coursetolec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coursetolec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coursetolec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cladd;
    private javax.swing.JButton clcan;
    private javax.swing.JTextField clcid;
    private javax.swing.JButton cldelete;
    private javax.swing.JTextField cllid;
    private javax.swing.JButton clreset;
    private javax.swing.JTable cltable;
    private javax.swing.JLabel cltext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
